### ISSUE TITLE
Beakjoon/1_Gold/1238_파티_G3.cpp 알고리즘 질문

### ISSUE THREAD

**Issue by jongyeon95** [kimdy003/AlgorithmStudy#1]
해당 문제에서 다익스트라 알고리즘을 사용하지 않고 플로이드와샬 알고리즘을 사용한 이유가 있나요?

**Comment by kimdy003** [comment]
저는 맨 처음 이 문제를 읽고 다익스트라 알고리즘보다는 플로이드와샬 알고리즘이 먼저 생각이나서 플로이드와샬 알고리즘으로 문제를 해결했습니다. 
플로이드와샬 알고리즘이 먼저 생각난 이유는 각 마을에서 X마을까지 최소 거리를 구하고 다시 X마을에서 시작한 마을까지의 거리를 더하면 되겠다고 생각했습니다.

**Comment by jongyeon95** [comment]
혹시 시간초과가 발생하지는 않았나요?
